(ns shx.cli
  "shx / envm command line entry point.

  Commands:
    render                 render the merged env config as bash (for eval)
    check                  diff the rendered env against the current env
    emit <bash|bb> <file>  emit an IR program file as bash or bb code
    validate <file>        validate an IR program file against shx.law.ir"
  (:gen-class)
  (:require [clojure.java.shell :as sh]
            [clojure.string :as str]
            [shx.domain.merge :as merge]
            [shx.infra.config :as cfg]
            [shx.infra.fs :as fs]
            [shx.law.ir :as law.ir]
            [shx.shape.bash :as bash]
            [shx.shape.bb :as bb]
            [shx.shape.quote :as q]))

(defn- resolved-config []
  (let [data (cfg/load-config (cfg/default-config-path))
        tree {:content (dissoc data :merge)
              :children (mapv cfg/read-fragment-tree (:merge data))}]
    (-> tree
        (merge/fold-fragment-tree)
        (merge/apply-host-overrides (cfg/hostname)))))

(defn render-env-bash
  "Render a resolved env config as bash text for eval in the current shell.

  Note: envm render semantics (render-time dir filtering, one PATH line)
  intentionally differ from IR :path/prepend (runtime guard). Converging
  them is a design decision, not a refactor detail."
  [config]
  (let [pre (fs/existing-dirs (:paths-prepend config))
        app (fs/existing-dirs (:paths-append config))]
    (str/join
     "\n"
     (concat
      ["# generated by shx - edit ~/.config/envm/env.edn, not your shell rc"]
      (for [[k v] (:vars config)]
        (bash/emit [:export {:name (name k) :value v}]))
      (when (seq pre)
        [(str "PATH=\"" (str/join ":" pre) "\"${PATH:+:$PATH}")])
      (when (seq app)
        [(str "PATH=\"${PATH:+$PATH:}\"" (q/dq (str/join ":" app)))])
      ["export PATH"
       ""
       "command -v dotenv >/dev/null 2>&1 || dotenv() { [ -f \"$1\" ] && set -a && . \"$1\" && set +a; }"]
      (for [[k v] (:aliases config)]
        (bash/emit [:alias {:name (name k) :argv [v]}]))
      (for [f (:source config)]
        (bash/emit [:source f]))
      (for [{:keys [guard cmd]} (:eval config)]
        (str "command -v " guard " >/dev/null 2>&1 && eval \"$(" cmd ")\""))
      ["true"]))))

(defn- env-after-eval
  "Evaluate script in a clean bash subshell and return the resulting env map."
  [script]
  (let [cmd (str "env -i HOME=\"$HOME\" bash --noprofile --norc -c "
                 (q/sq (str script "\nenv")))
        {:keys [out]} (sh/sh "bash" "-c" cmd)]
    (->> (str/split-lines out)
         (map #(str/split % #"=" 2))
         (filter #(= 2 (count %)))
         (into {}))))

(defn- path-set [env]
  (set (str/split (get env "PATH" "") #":")))

(defn check
  "Diff the rendered env against the current process env and print a report."
  [config]
  (let [rendered (env-after-eval (render-env-bash config))
        now (into {} (System/getenv))
        managed (set (map name (keys (:vars config))))
        changed (for [k managed
                      :let [a (get now k) b (get rendered k)]
                      :when (and a b (not= a b))]
                  [k a b])
        missing-path (remove (path-set rendered) (path-set now))
        dupes-now (- (count (str/split (get now "PATH" "") #":"))
                     (count (path-set now)))]
    (println "== shx check ==")
    (println "current PATH entries:" (count (str/split (get now "PATH" "") #":")))
    (println "current PATH duplicates:" dupes-now)
    (println)
    (if (seq changed)
      (do (println "vars that would CHANGE:")
          (doseq [[k a b] changed]
            (println " " k)
            (println "   now:     " a)
            (println "   rendered:" b)))
      (println "all managed vars match current values"))
    (println)
    (if (seq missing-path)
      (do (println "PATH entries in current env but NOT rendered:")
          (doseq [p missing-path] (println "  -" p)))
      (println "no PATH coverage gaps"))))

(defn -main [& [cmd & args]]
  (case cmd
    "render" (println (render-env-bash (resolved-config)))
    "check" (check (resolved-config))
    "emit" (let [[target file] args
                 program (cfg/read-edn-file file)]
             (when-not program
               (System/exit 1))
             (case target
               "bash" (println (bash/emit-program program))
               "bb" (println (bb/emit-program program))
               (do (cfg/warn "unsupported emit target:" target)
                   (System/exit 1))))
    "validate" (let [[file] args
                     program (cfg/read-edn-file file)]
                 (if (law.ir/valid-program? program)
                   (println "valid IR program")
                   (do (println (pr-str (law.ir/explain-program program)))
                       (System/exit 1))))
    (do (println "usage: shx render | shx check | shx emit <bash|bb> <file> | shx validate <file>")
        (System/exit 1))))
